### ISSUE TITLE
Error defining a list with only one element

### ISSUE THREAD

**Issue by zaid** [bitwalker/conform#112]
Hi,

I'm having an issue where running ```conform.effective``` fails with the following error:

```elixir
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:type, 'memory'}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1776: Enum.map/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/conform/translate.ex:132: anonymous fn/6 in Conform.Translate.convert_types/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/conform/translate.ex:129: Conform.Translate.convert_types/2
    lib/conform/translate.ex:95: Conform.Translate.apply_schema/2
```

The issue happens when I have a list of {:atom, :binary} and the list has only one element. My current work-around is to add another dummy element that I ignore.

I am running the latest versions of conform (2.2.2) and distillery (1.2.2) and the relevant section of my schema / config are:

```elixir
"evl_daemon.storage_engines": [
  commented: false,
    datatype: [
      list: [list: {:atom, :binary}]
    ],  
    default: [
      [type: "memory", maximum_events: "100"]
    ],  
    doc: "Enabled storage engines and their options.",
    hidden: false,
    to: "evl_daemon.storage_engines"
],  
```

The relevant entry in the config file is:
```elixir
evl_daemon.storage_engines = [type = "memory", maximum_events = "100"]
```

Am I doing something wrong in my schema which is triggering this issue?

**Comment by zaid** [comment]
This looks similar to issue #68

**Comment by bitwalker** [comment]
@zaid I'll take a look at this first thing tomorrow. Thanks for the report!

**Comment by bitwalker** [comment]
I've got this fixed locally, just addressing some other outstanding issues before pushing a new release :)

**Comment by zaid** [comment]
Perfect! I'll test it as soon as you push your changes. Thank you for fixing this so fast 👍

**Comment by bitwalker** [comment]
I've pushed the fixes to master, could you give it a shot?

**Comment by zaid** [comment]
I just gave it a quick test and it is giving me a different error now:

```elixir
** (Conform.Translate.TranslateError) Invalid value for evl_daemon.zones: Expected value of type `:binary`, got ['[1', 'Front door', ']', '[2', 'Garage door', ']', '[3', 'Basement door', ']', '[4', 'Kitchen door', ']', '[5', 'Office motion sensor', ']', '[6', 'Family room motion sensor', ']', '[7', 'Basement glass break sensor', ']', '[8', 'Basement motion sensor', ']']
    lib/conform/translate.ex:328: Conform.Translate.parse_datatype/3
    lib/conform/translate.ex:145: anonymous fn/6 in Conform.Translate.convert_types/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/conform/translate.ex:142: Conform.Translate.convert_types/2
    lib/conform/translate.ex:108: Conform.Translate.apply_schema/2
    lib/conform/translate.ex:84: Conform.Translate.to_config/3
    lib/mix/tasks/conform.effective.ex:106: Mix.Tasks.Conform.Effective.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
```
The config file that I tested with can be found [here](https://github.com/Tokenize/evl-daemon-elixir/blob/master/config/evl_daemon.conf.sample)

The schema file can be found [here](https://github.com/Tokenize/evl-daemon-elixir/blob/master/config/evl_daemon.schema.exs)

The entry that it is failing on is parsed using a transformer so I'm wondering if the reason for failure is because of that (since I don't explicitly define the datatype in the mapping section).

**Comment by bitwalker** [comment]
Ok, you should be good to go on master now, can you confirm before I cut a new release?

**Comment by zaid** [comment]
I'm still having an error when it tries to parse evl_daemon.zones. Here is the error message:

```elixir
** (Conform.Translate.TranslateError) Invalid value for evl_daemon.zones: Expected value of type `:binary`, got [['1', 'Front door'], ['2', 'Garage door'], ['3', 'Basement door'], ['4', 'Kitchen door'], ['5', 'Office motion sensor'], ['6', 'Family room motion sensor'], ['7', 'Basement glass break sensor'], ['8', 'Basement motion sensor']]
    lib/conform/translate.ex:328: Conform.Translate.parse_datatype/3
    lib/conform/translate.ex:145: anonymous fn/6 in Conform.Translate.convert_types/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/conform/translate.ex:142: Conform.Translate.convert_types/2
    lib/conform/translate.ex:108: Conform.Translate.apply_schema/2
    lib/conform/translate.ex:84: Conform.Translate.to_config/3
    lib/mix/tasks/conform.effective.ex:106: Mix.Tasks.Conform.Effective.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
```

My mix.lock shows the following entry for conform:

```elixir
"conform": {:git, "https://github.com/bitwalker/conform.git", "facff314c16436228134e044a41c54fc0648dbc0", []},
```

Let me know if I'm doing something wrong.

**Comment by bitwalker** [comment]
Oh sorry, could you look in the `test/schemas/evl_daemon.schema.exs` file? You'll see the change I had to make to the mappings/transforms for that and the `partitions` option. Transforms are executed *after* mappings are done, so you have to define a valid datatype for the initial value, even if you transform it into something totally different later.

**Comment by zaid** [comment]
Oh that explains it. I just made the same changes and verified that ```conform.effective``` is returning the expected results.

Thank you for fixing this 👍
